import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {Header} from "@/components/ui/Header";
import {Footer} from "@/components/ui/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RPC LIMO",
  description: "Generated by create next app",
    icons:{
      icon:[
          {
              url: "/logocompany.png",
              alt: "RPC LIMO Logo",
              type: "image/png",
              sizes: "512x512",
          },

      ]
    }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header />

        {children}
      </body>
    <Footer/>
    </html>
  );
}
